# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Keyuan_Dream(object):
    def setupUi(self, Keyuan_Dream):
        Keyuan_Dream.setObjectName("Keyuan_Dream")
        Keyuan_Dream.resize(1275, 855)
        Keyuan_Dream.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.gridLayout_3 = QtWidgets.QGridLayout(Keyuan_Dream)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(Keyuan_Dream)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget_3 = QtWidgets.QListWidget(self.widget)
        self.listWidget_3.setMinimumSize(QtCore.QSize(0, 50))
        self.listWidget_3.setMaximumSize(QtCore.QSize(16777215, 41))
        self.listWidget_3.setStyleSheet("QListWidget {  \n"
" background-color: rgb(0, 0, 0);\n"
" border: 1px solid; \n"
" font-family: Microsoft YaHei; \n"
" font-size: 10px;  \n"
" color: rgb(255, 255, 255);\n"
" flex-direction: row; \n"
" padding: 5px; } \n"
"QListWidget::item { padding: 5px; width: 150px; height: 20px; } QListWidget::item:hover { \n"
" background-color: transparent;\n"
" padding: 10px;\n"
" border-bottom: 3px solid rgb(130, 130, 130);\n"
" }")
        self.listWidget_3.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.listWidget_3.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(Keyuan_Dream)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.Monitoring_interface = QtWidgets.QWidget()
        self.Monitoring_interface.setObjectName("Monitoring_interface")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Monitoring_interface)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.Monitoring_interface)
        self.widget_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.seror1_data = QtWidgets.QLabel(self.widget_2)
        self.seror1_data.setStyleSheet("color: rgb(255, 255, 255);")
        self.seror1_data.setObjectName("seror1_data")
        self.gridLayout.addWidget(self.seror1_data, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.seror2_data = QtWidgets.QLabel(self.widget_2)
        self.seror2_data.setStyleSheet("color: rgb(255, 255, 255);")
        self.seror2_data.setObjectName("seror2_data")
        self.gridLayout.addWidget(self.seror2_data, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.seror3_data = QtWidgets.QLabel(self.widget_2)
        self.seror3_data.setStyleSheet("color: rgb(255, 255, 255);")
        self.seror3_data.setObjectName("seror3_data")
        self.gridLayout.addWidget(self.seror3_data, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.seror4_data = QtWidgets.QLabel(self.widget_2)
        self.seror4_data.setStyleSheet("color: rgb(255, 255, 255);")
        self.seror4_data.setObjectName("seror4_data")
        self.gridLayout.addWidget(self.seror4_data, 3, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.btn_start = QtWidgets.QPushButton(self.widget_2)
        self.btn_start.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout_4.addWidget(self.btn_start)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.plot_view = QChartView(self.Monitoring_interface)
        self.plot_view.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plot_view.setObjectName("plot_view")
        self.horizontalLayout_2.addWidget(self.plot_view)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.Monitoring_interface)
        self.Main_interface = QtWidgets.QWidget()
        self.Main_interface.setObjectName("Main_interface")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Main_interface)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.Main_interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_8.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_8.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 0, 4, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_17.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_17.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_17.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 0, 6, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_16.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_16.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_16.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_2.addWidget(self.pushButton_16, 0, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_18.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_18.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_18.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 0, 7, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_10.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_10.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_10.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 0, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_19.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_19.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_19.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 0, 8, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_15.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_15.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_15.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 0, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_11.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_11.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_11.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 0, 5, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_9.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_9.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_9.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 1, 6, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_14.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_14.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_14.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 1, 5, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_7.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 1, 4, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.Main_interface)
        self.pushButton_12.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_12.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_12.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255,255,255);  \n"
"border-radius: 30px;  border: 2px groove gray;\n"
"font: 9pt \"AcadEref\";\n"
"border-style: outset;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 2, 5, 1, 1)
        self.stackedWidget.addWidget(self.Main_interface)
        self.dingwei = QtWidgets.QWidget()
        self.dingwei.setObjectName("dingwei")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dingwei)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dingwei1 = QtWidgets.QWidget(self.dingwei)
        self.dingwei1.setObjectName("dingwei1")
        self.gridLayout_4.addWidget(self.dingwei1, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.dingwei)
        self.gridLayout_3.addWidget(self.stackedWidget, 1, 0, 1, 1)

        self.retranslateUi(Keyuan_Dream)
        self.stackedWidget.setCurrentIndex(2)
        self.btn_start.clicked.connect(Keyuan_Dream.gengxin)
        self.pushButton_16.clicked.connect(Keyuan_Dream.zidong)
        self.pushButton_15.clicked.connect(Keyuan_Dream.shoudong)
        self.pushButton_10.clicked.connect(Keyuan_Dream.disu)
        self.pushButton_8.clicked.connect(Keyuan_Dream.zhongsu)
        self.pushButton_11.clicked.connect(Keyuan_Dream.gaosu)
        self.pushButton_7.clicked.connect(Keyuan_Dream.zuozhuan)
        self.pushButton_14.clicked.connect(Keyuan_Dream.kaishi)
        self.pushButton_9.clicked.connect(Keyuan_Dream.youzhuan)
        self.pushButton_12.clicked.connect(Keyuan_Dream.houtui)
        self.listWidget_3.itemClicked['QListWidgetItem*'].connect(Keyuan_Dream.changePage)
        self.pushButton_17.clicked.connect(Keyuan_Dream.dingdian)
        self.pushButton_18.clicked.connect(Keyuan_Dream.tingzhi)
        self.pushButton_19.clicked.connect(Keyuan_Dream.jiting)
        QtCore.QMetaObject.connectSlotsByName(Keyuan_Dream)

    def retranslateUi(self, Keyuan_Dream):
        _translate = QtCore.QCoreApplication.translate
        Keyuan_Dream.setWindowTitle(_translate("Keyuan_Dream", "Form"))
        self.label.setText(_translate("Keyuan_Dream", "智能小船"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("Keyuan_Dream", "数据监控"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("Keyuan_Dream", "操作界面"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("Keyuan_Dream", "定位"))
        item = self.listWidget_3.item(3)
        item.setText(_translate("Keyuan_Dream", "摄像头"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Keyuan_Dream", "浑浊度"))
        self.seror1_data.setText(_translate("Keyuan_Dream", "传感器1数据"))
        self.label_3.setText(_translate("Keyuan_Dream", "电压"))
        self.seror2_data.setText(_translate("Keyuan_Dream", "传感器1数据"))
        self.label_4.setText(_translate("Keyuan_Dream", "PH"))
        self.seror3_data.setText(_translate("Keyuan_Dream", "传感器1数据"))
        self.label_5.setText(_translate("Keyuan_Dream", "深度"))
        self.seror4_data.setText(_translate("Keyuan_Dream", "传感器1数据"))
        self.btn_start.setText(_translate("Keyuan_Dream", "更新"))
        self.pushButton_8.setText(_translate("Keyuan_Dream", "中速"))
        self.pushButton_17.setText(_translate("Keyuan_Dream", "定点"))
        self.pushButton_16.setText(_translate("Keyuan_Dream", "自动"))
        self.pushButton_18.setText(_translate("Keyuan_Dream", "停止"))
        self.pushButton_10.setText(_translate("Keyuan_Dream", "低速"))
        self.pushButton_19.setText(_translate("Keyuan_Dream", "急停"))
        self.pushButton_15.setText(_translate("Keyuan_Dream", "手动"))
        self.pushButton_11.setText(_translate("Keyuan_Dream", "高速"))
        self.pushButton_9.setText(_translate("Keyuan_Dream", "右转"))
        self.pushButton_14.setText(_translate("Keyuan_Dream", "开始"))
        self.pushButton_7.setText(_translate("Keyuan_Dream", "左转"))
        self.pushButton_12.setText(_translate("Keyuan_Dream", "后退"))
from PyQt5.QtChart import QChartView
