# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(251, 594)
        Form.setMinimumSize(QtCore.QSize(251, 594))
        Form.setMaximumSize(QtCore.QSize(251, 594))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 251, 594))
        self.widget.setMinimumSize(QtCore.QSize(251, 594))
        self.widget.setMaximumSize(QtCore.QSize(251, 594))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 72, 15))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setGeometry(QtCore.QRect(0, 70, 251, 191))
        self.listWidget.setStyleSheet("QListView::item {\n"
"    height: 60px;    \n"
"}\n"
"QListView {\n"
"    font: 25 9pt \"Microsoft YaHei\";\n"
"    border: 5px solid white;\n"
"    border-radius: 15px;\n"
"    selection-color: black;\n"
"}\n"
"QListView::item:hover {\n"
"    background-color: transparent;\n"
"    padding: 10px;\n"
"    border-left: 3px solid rgb(130, 130, 130);\n"
"}\n"
"QListView::item:selected {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    padding: 10px;\n"
"    border-left: 3px solid black;\n"
"}\n"
"")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.listWidget.addItem(item)

        self.retranslateUi(Form)
        self.listWidget.itemClicked['QListWidgetItem*'].connect(Form.selection_function)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "名字"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "监控界面"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "位置"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "远程监控"))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
